### ISSUE TITLE
Logging backend should not be a transitive dependency

### ISSUE THREAD

**Issue by reckart** [amithkoujalgi/ollama4j#1]
Ollama4j uses logback as a logging backend and has a transitive dependency on it.

Libraries should not have transitive dependencies on logging backends.

If you need the backend during testing, best use the `test` scope on the dependency.

In general, the application which uses the ollama4j library should define a logging backend for ollama4j to use.

**Comment by reckart** [comment]
Also, to avoid conflicts with the logging configuration of the application using the library, the library should not include a logging configuration file like `logback.xml` in `src/main` - if a configuration is needed for logging during testing, it should be in `src/test`.

**Comment by amithkoujalgi** [comment]
Thanks for pointing out the issues @reckart. I'll push the changes for these ASAP.

**Comment by reckart** [comment]
Looks good, thanks :)
