### ISSUE TITLE
Set options / temperature

### ISSUE THREAD

**Issue by michaelwechner** [amithkoujalgi/ollama4j#16]
According to the Ollama documentation one can set the temperature using options

https://github.com/jmorganca/ollama/blob/main/docs/api.md#parameters
https://github.com/jmorganca/ollama/blob/main/docs/modelfile.md#valid-parameters-and-values

{ "model": "mistral", "stream":false, "prompt":"How many moons does earth have?", "options":{"temperature":0} }

IIUC one cannot set the temperature / options yet using ollama4j.

I would like to suggest to introduce another "ask" method, where one can set options as well

Options options = new Options();
options.setTemperature(0.7);
ollamaAPI.ask(String, String, Options)

WDYT?

Thanks

Michael

**Comment by michaelwechner** [comment]
Please see PR https://github.com/amithkoujalgi/ollama4j/pull/17

**Comment by amithkoujalgi** [comment]
Thank you so much for the PR @michaelwechner. Just a few moments ago I pushed the code set options for `ask` API and then I saw your PR!
I really appreciate your effort in adding support for options. Although I have added support for all the available [params](https://github.com/jmorganca/ollama/blob/main/docs/modelfile.md#valid-parameters-and-values) as [options](https://amithkoujalgi.github.io/ollama4j/apidocs/io/github/amithkoujalgi/ollama4j/core/utils/OptionsBuilder.html).

I've updated the docs too:
- https://amithkoujalgi.github.io/ollama4j/docs/apis-extras/options-builder
- https://amithkoujalgi.github.io/ollama4j/docs/apis-ask/ask

**Comment by michaelwechner** [comment]
Sure, no problem @amithkoujalgi

Thanks for adding the Options functionality!

It would be great if you could update maven https://central.sonatype.com/artifact/io.github.amithkoujalgi/ollama4j :-)

**Comment by amithkoujalgi** [comment]
@michaelwechner you're welcome! 🙂

I have been trying to push the latest artifact to Maven central, but the builds are constantly failing due to some issues with their servers. I have created a [ticket](https://issues.sonatype.org/browse/OSSRH-97975) and I am waiting for their response with a resolution.

As soon as the issue is resolved, I shall trigger the build again and have the artifact published.

**Comment by michaelwechner** [comment]
Great, thank you very much @amithkoujalgi 

For the moment we use our own Maven server for the most recent ollama4j version, but I would prefer to switch back to your official version :-)

**Comment by amithkoujalgi** [comment]
Alright @michaelwechner, I got an update from the Maven central team and they've got the issue resolved.
I have run the GH action to push the artifact to Maven central and the latest version has now been published. 🚀

Please try it out. Thanks!🙂

**Comment by michaelwechner** [comment]
Thank you very much @amithkoujalgi, works very fine!

**Comment by amithkoujalgi** [comment]
Great! Thanks for the update @michaelwechner.
