### ISSUE TITLE
Certain requests fail with a 400 Bad Request

### ISSUE THREAD

**Issue by reckart** [amithkoujalgi/ollama4j#2]
It appears that certain requests generated by the `ask()` method trigger a `400 - Bad request` on the side of ollama.

Trying the same request manually works though (i.e. copying the JSON generated by `ollamaRequestModel.toString()` and posting it manually).

**Comment by amithkoujalgi** [comment]
Are you still seeing the issue after updating the `writeBytes` code?

**Comment by reckart** [comment]
No, with the change from https://github.com/amithkoujalgi/ollama4j/pull/3, all requests I send return 200 and a proper response.

**Comment by reckart** [comment]
The issue may persist in other methods though - e.g. you should probably also update `askAsync()`  and maybe check other methods if they make the same call.

**Comment by amithkoujalgi** [comment]
Thanks! I've updated the `askAsync` method too: https://github.com/amithkoujalgi/ollama4j/commit/df9b9af0635a983b55411bb904cda5f33b42b292
