### ISSUE TITLE
Update Code Due to Changes in generate Method of PromptBuilder

### ISSUE THREAD

**Issue by anjeongkyun** [amithkoujalgi/ollama4j#32]
### Description
The generate method of PromptBuilder has undergone changes due to recent updates. Consequently, the code provided in the example no longer functions correctly.

Previously, the method was called as follows:

```java
OllamaResult response = ollamaAPI.generate(model, promptBuilder.build());
```
However, in the latest version, additional options need to be passed to the generate method. Therefore, the code needs to be modified as follows:

```java
OllamaResult response = ollamaAPI.generate(model, promptBuilder.build(), new Options());
```
Updating the code to reflect this change should prevent any further compatibility issues.

**Comment by amithkoujalgi** [comment]
Thanks for the PR @anjeongkyun. I've merged it.
