### ISSUE TITLE
Thanks for creating

### ISSUE THREAD

**Issue by bodiam** [amithkoujalgi/ollama4j#36]
Hi @amithkoujalgi ,

Thanks for creating this library! I've just implemented it in an experimental project for our Open Source library, Datafaker.net.

You can find the repo here should you be interested: https://github.com/datafaker-net/datafaker-experimental/tree/main/ollama-api

Cheers,
Erik

**Comment by amithkoujalgi** [comment]
Hi @bodiam,

Thank you for reaching out and for implementing Ollama4j in your project for Datafaker.net! It's exciting to see the library being used in such innovative ways.

I've had a look at the Datafaker library, and it appears to be a valuable tool for generating fake data. Combining it with Ollama4j for fake data generation is a brilliant idea. Great work!

I've added Datafaker to the list of Ollama4j usages/implementations here: https://github.com/amithkoujalgi/ollama4j?tab=readme-ov-file#whos-using-ollama4j 😃 

Best regards,
Amith
