### ISSUE TITLE
Adds test case of OllamaChatRequestBuilder

### ISSUE THREAD

**Issue by anjeongkyun** [amithkoujalgi/ollama4j#38]
I felt there was a lack of test cases for OllamaChatRequestBuilder, so I added tests for a few methods.
If there are any mistakes, please comment🙇‍♂️

PR. https://github.com/amithkoujalgi/ollama4j/pull/37

**Comment by amithkoujalgi** [comment]
Thanks for the PR @anjeongkyun!
