### ISSUE TITLE
`evalCount` in response from ollama cannot be parsed

### ISSUE THREAD

**Issue by reckart** [amithkoujalgi/ollama4j#4]
I sometimes get the error

>  UnrecognizedPropertyException: Unrecognized field "eval_count" (class io.github.amithkoujalgi.ollama4j.core.models.OllamaResponseModel), not marked as ignorable (11 known properties: "response", "done", "evalCount", "eval_duration", "model", "created_at", "prompt_eval_duration", "load_duration", "context", "prompt_eval_count", "total_duration"])

**Comment by amithkoujalgi** [comment]
I believe this is fixed now. Could you verify? If it is fixed, I can close the issue.

**Comment by reckart** [comment]
Should be fixed. If I encounter it again, I'll re-open or open a new issue.
