### ISSUE TITLE
does this 1.0.64 version support LLaMa3?

### ISSUE THREAD

**Issue by PassiveIncomeMachine** [amithkoujalgi/ollama4j#40]
does this 1.0.64 version support LLaMa3?

**Comment by amithkoujalgi** [comment]
If you mean `"is LLaMA3 available as one of the model types?"`, then yes. 

Refer: https://github.com/amithkoujalgi/ollama4j/blob/main/src/main/java/io/github/amithkoujalgi/ollama4j/core/types/OllamaModelType.java#L13
