### ISSUE TITLE
:package: Deliver as Jitpack :sloth: 

### ISSUE THREAD

**Issue by adriens** [amithkoujalgi/ollama4j#58]
# :grey_question: About

Currently, the setup is pretty complex for end-users : 

![image](https://github.com/user-attachments/assets/7de4d416-16f5-4767-9e34-8e8126e486bd)

Wihtout having to push to maven central repos and with minimal effort, this could be enhanced with [jitpack](https://jitpack.io/) : 

![image](https://github.com/user-attachments/assets/8c8a2df4-f292-4cca-aee2-5bce00d5049e)

# :dart: Action

- [ ] Consider document it this way
- [ ] Add the [`markdown` badge](https://shields.io/badges/jit-pack) so people are aware it is available as a jitpack dependency

**Comment by amithkoujalgi** [comment]
Thanks for pointing out @adriens! I've update the instructions in [readme](https://github.com/amithkoujalgi/ollama4j?tab=readme-ov-file#using-jitpack).

Cheers!
