### ISSUE TITLE
Change your logo with Duke instead

### ISSUE THREAD

**Issue by stephanj** [amithkoujalgi/ollama4j#7]
Friendly suggestion that it would be better to use the Java Duke logo instead of the TM Java logo.  I speak out of experience :)   Otherwise very interesting project, keep it up! 
![IMG_5744](https://github.com/amithkoujalgi/ollama4j/assets/179457/18285406-664e-4201-b644-9e0178b5b5f5)

**Comment by amithkoujalgi** [comment]
Thanks @stephanj! I'll update the logo. Thanks for the image and suggestion 😀

**Comment by amithkoujalgi** [comment]
I've updated the logo. Closing the issue.
